language: node_js
node_js:
  - "stable"
  - "unstable"
  - "4"

sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "unstable"

after_success:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
